### ISSUE TITLE
Windows Firewall

### ISSUE THREAD

**Issue by gaboAcosta** [request/request-debug#8]
Hello, we are using request promise and specifically on windows we have an error where the firewall will send a SIGTERM to our node app, I am extremely suspicious this has to do with Windows firewall.

When the request promise library tries to send a request and with debug enabled, we can see that the request.callback and the request.handler come both undefined.

Is there any place documenting the pains implementing on windows might have? or even better, a tutorial to see the correct config, thanks for the support

**Comment by XMB5** [comment]
https://github.com/request/request-debug/blob/54a0fea933e7fab12c9dc7d6155a7a0ebd4f41c7/index.js#L15

It tries to connect to localhost port 4 which triggers the firewall
