### ISSUE TITLE
Is that possible to debug only one instance of request?

### ISSUE THREAD

**Issue by PavloPoliakov** [request/request-debug#9]
Hi,

Imagine I have `requestA` and `requestB`. While I need to debug only one instance.

Here is the sample code:

``` javascript
'use strict';
const _ = require('lodash');
let requestA = _.cloneDeep(require('request'));
let requestB = _.cloneDeep(require('request'));

require('request-debug')(requestA);

requestA.get('http://yandex.ru', (error, response, body) => {
    console.log('--- A ---');
    console.log(response.statusCode);
    console.log('--- / A ---')
});
requestB.get('http://yandex.ru', (error, response, body) => {
    console.log('--- B ---');
    console.log(response.statusCode);
    console.log('--- / B ---')
});
```

As you see in console - both request would receive the debug output.

How it's possible to configure the debug only for the `requestA` instance?

**Comment by eiriksm** [comment]
Well, you could do as suggested in the README, specify your own handler and inspect the debugId property of the data object. 

Could something like this help you, perhaps?

``` js
'use strict';
const request = require('request');
require('request-debug')(request, function(type, data, r) {
  if (data.debugId === 1) {
    console.log(arguments);
  }
});

request.get('http://yandex.ru', (error, response, body) => {
  console.log('--- A ---');
  console.log(response.statusCode);
  console.log('--- / A ---')
});

request.get('http://yandex.ru', (error, response, body) => {
  console.log('--- B ---');
  console.log(response.statusCode);
  console.log('--- / B ---')
});
```

Hope that helps :)

**Comment by PavloPoliakov** [comment]
Hi @eiriksm ,

Sorry, I haven't got how should I put custom `debugId` to the requestA, for example?
I haven't found anything about this in the README as well. Could you, please, clarify?

Regards

**Comment by eiriksm** [comment]
Hi, sorry for the bad explanation.

The debug id will be in the order in which you initiate the requests.

So in your case, request A will be debugId 1. 

Granted, there is nothing in the README about specifying a custom debug id. It is currently not possible. But it will increment for each incremental request.

Also, I guess the information you are looking for is combined in two sentences a couple of paragraphs apart:

```
You can also specify a function to handle request or response data

require('request-debug')(request, function(type, data, r) {
    // put your request or response handling logic here
});
```

...and then further down:

> You can use the data.debugId parameter to match up requests with their responses and other events.

So it is indeed a little apart, but I would assume that could cover the use case you are looking for? 

You could also do something like setting a custom header for the request you want to debug. Kind of like is suggested in this PR: https://github.com/request/request-debug/pull/10/files

Hope that helps! :)

**Comment by PavloPoliakov** [comment]
Clear, that makes more sense.

However, I think even debug disabling header doesn't make sense for me.
It would not cover the next case:
1. I have an app, which uses request
2. I require my custom module, among the module configuration it's stated that this module requests should be debugged 
3. As soon as I have required the module - all the requests are now under the `debug` mode

The `debugId` is not ok, because it's not possible to count all the queries which I make.
The debug header is better, however for my case I need an option to enable debug on demand, not to disable.

Anyhow, now it's much clearer.

Thanks!

**Comment by eiriksm** [comment]
> The debug header is better, however for my case I need an option to enable debug on demand, not to disable.

That was my point also. The link was just an example how you can use a header to respond in the debug handler, and thus enabling or disabling on demand.

So what I meant you could also do was:

``` js
'use strict';
const _ = require('lodash');
const request = require('request');
require('request-debug')(request, function(type, data, r) {
  // Check if r (the request object) has your custom header set.
});

request.get({
  uri: 'http://yandex.ru', 
  headers: {
    'x-something-super-custom': true
  }, (error, response, body) => {
    console.log(response.statusCode);
});
```

**Comment by PavloPoliakov** [comment]
true, thought we were talking about the possible module update.

Thanks for the help! And thanks for the module!

Regards,

**Comment by eiriksm** [comment]
Glad I could help!
